### ISSUE TITLE
Existing dates are immediately overwritten by current dates, ng-bind must be moment object(?)

### ISSUE THREAD

**Issue by Jurigag** [atais/angular-eonasdan-datetimepicker#12]
Plunkr: http://plnkr.co/edit/C5eIVre55XUFbCet5c8p

Even when i set it as defaultDate, or set useCurrent to false it's still happening, right now this is causing me to not using this.

**Comment by Jurigag** [comment]
Well changing it to:

`vm.date = moment('2016/05/13/ 21:22','YYYY/MM/DD HH:mm');` fix a problem

But shouldn't it accept string anyway ? If i run it with defaultDate without directive i can provide just string.

Actually changing this line:

https://github.com/atais/angular-eonasdan-datetimepicker/blob/master/dist/angular-eonasdan-datetimepicker.js#L60

to `moment($scope.date,$scope.options.format)` fixes a problem

I just changed this line to:

```

if ($scope.options && $scope.options.format) {
    ngModel.$setViewValue(moment($scope.date, $scopt.options.format));
}
else {
    ngModel.$setViewValue(moment($scope.date));
}
```

**Comment by atais** [comment]
As you have found out, currently `moment object` is preferred. I have added the default conversion, because I often faced `Date` objects in my application that I did not want to transform manually.

In your case it is best if you parse the `String` on your own and provide a proper object to the directive, as you mentioned: 

`vm.date = moment('2016/05/13/ 21:22','YYYY/MM/DD HH:mm');`

Your requested change has one major issue. If you would have a date `String` in `formatA` and you would like to use `formatB` in the `datetimepicker` you would have to still manually convert the type.

I understand that the change seems natural in this case, but I try to keep the directive as general and easy to use as possible. Hope you will still enjoy it. 

Thanks.
