### ISSUE TITLE
Different behaviour with bootstrap-datetimepicker 4.17.42 vs. 4.17.37

### ISSUE THREAD

**Issue by anx-ckreuzberger** [atais/angular-eonasdan-datetimepicker#15]
Hi!
Based on your Simple example with one datetimepicker http://plnkr.co/edit/n8L8UZ I discovered a problem, and I'm not sure if this is more a problem of the bootstrap-datetimepicker or with this angular directive. Nevertheless, I thought I should report it.

Expected behaviour (works with 4.17.37):
(Open the plunkr above and run it)
Press Add +1w about 5 times (it MUST jump you to at least one month later then the current month)
Press the calendar icon
The selected day and the selected month should appear

With 4.17.42 this does not work.
See also the two uploaded screencasts (as GIF)

![error_optimized](https://cloud.githubusercontent.com/assets/18396259/20000130/4ba088da-a276-11e6-9f3c-764120441945.gif)
![expected_optimized](https://cloud.githubusercontent.com/assets/18396259/20000129/4b9f0e92-a276-11e6-9140-8663d4e5b0d7.gif)

**Comment by anx-ckreuzberger** [comment]
eonasdan-bootstrap-datetimepicker@4.17.43 has the same issue as 4.17.42. 

Also, 4.17.37 can NOT be installed using npm... 

> npm ERR! notarget No compatible version found: eonasdan-bootstrap-datetimepicker@4.17.37
> npm ERR! notarget Valid install targets:
> npm ERR! notarget 4.17.43, 4.17.42, 4.15.35, 4.14.30, 4.7.14, 3.1.3

This pretty much leaves this angular library in a spot where it does not work as expected (when using npm), unless you are willing to use a CDN version of the datetimepicker or download it manually or use npm install git+https://...

**Comment by atais** [comment]
Well cutting long story short... if by changing the version of date-time picker you observe different behaviour it is not the problem of the directive.

Myself I am using bower for dependencies because they rely on GitHub tags.

To sum up, I understand your problems, though all of them should be posted on library's GitHub and are really not in my decision to be fixed or not. The library itself has a maintenance problem and was not updated for a long time. I also suggest using `master` version directly from GitHub. The pull requests there were occasionally accepted. I use `4.17.37` from bower.

**Comment by anx-ckreuzberger** [comment]
Then you still run into the problem of new users that install your package will get version 4.17.43 automatically:

``` bash
bower install angular-eonasdan-datetimepicker --save

angular-eonasdan-datetimepicker#0.3.7 bower_components/angular-eonasdan-datetimepicker
├── angular#1.5.8
├── bootstrap#3.3.7
├── eonasdan-bootstrap-datetimepicker#4.17.43
├── jquery#2.2.4
└── moment#2.15.2

jquery#2.2.4 bower_components/jquery

angular#1.5.8 bower_components/angular

bootstrap#3.3.7 bower_components/bootstrap
└── jquery#2.2.4

eonasdan-bootstrap-datetimepicker#4.17.43 bower_components/eonasdan-bootstrap-datetimepicker
├── jquery#2.2.4
└── moment#2.15.2

moment#2.15.2 bower_components/moment
```

It's definately good that one can get 4.17.37 by using bower, though with so many people abbandoning bower in favour of npm (npm is even the first installation method mentioned in the README) I believe we should find a fix.

edit: on that note, temporary fix for bower:

``` bash
bower install eonasdan-bootstrap-datetimepicker#4.17.37 --save
```

temporary fix for npm

``` bash
npm install git+https://github.com/Eonasdan/bootstrap-datetimepicker.git#4.17.37 --save
```

**Comment by atais** [comment]
To be honest I totally understand you, but still I have no answer other than manually selecting the version. I was not even aware of the bugs you have just  pointed out in the newest version and probably most of the users did not use those "corner cases" as well :smile: 

I wonder if the bug above could be anyhow connected to #14 so let me fix that one first and I will try to focus here later.

**Comment by anx-ckreuzberger** [comment]
Could be connected. One way to "fix" this issue was to call setDefault(ngModel.$viewValue) in ngmodel.$render, which would overwrite the default value.
Though I'm pretty sure this is not the way it's intended to work.

**Comment by atais** [comment]
Tested with `0.3.8` but the library version `4.17.42` still shows wrong month.

**Comment by atais** [comment]
@anx-ckreuzberger It is a feature :smile_cat: 

The calendar was designed in a manner that if the selected day is still visible on the previous month's page it does not change the page. In your example: 

On the November's page you can see two rows of days from December and in `4.17.42` until the 13.12.2016 is reached the next page is not loaded (because it is not required). Maybe there is an option for that, but it is not a bug.
