### ISSUE TITLE
How to use $validators

### ISSUE THREAD

**Issue by rodrigosaling** [atais/angular-eonasdan-datetimepicker#4]
Hello!

I am currently using the diosney directive to load the datetimepicker on my application, and with it I am using some `$validators` to test a group of dates on a page. Right now it is working fine because diosney's solution uses the `ng-model` on each `<input>`, but I want to be able to open the datetimepicker by clicking on the button, like your examples. This is an example of my code:

```
<input type="text" class="form-control" name="delivery_to" id="delivery-to" 
    ng-model="vm.deliveryTo" required validate-after-date="delivery_form.delivery_from"
    datetimepicker datetimepicker-options="{{ vm.getDateTimePickerOptions() }}">
```

But with your code, the model is declared with the `date` attribute on the `div.input-group`. **How do I use the same validation but with your directive?** I am testing some modifications on your plunker, but it's throwing a lot of errors.

Now I see that you update the maxDate on `on-change` event... By using this approach I would have to modify a lot of code, but maybe it's a solution.

**Comment by rodrigosaling** [comment]
Well, I found some issues with my code and after fixing them, I managed to make the validators work by declaring the `ng-model` to the `<input>`:

```
<div class="input-group" datetimepicker date="vm.dateFrom" options="vm.options">
    <input type="text" name="dateFrom" id="dateFrom" class="form-control"
           ng-model="vm.dateFrom" validate-before-date="dates_form.dateTo">
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
</div>
```

But if I try to type the date on the input field, it tries to parse the text after each character, and that's not good.

**Comment by atais** [comment]
@rodrigosaling could you present the plunker that you mentioned?

So to sum up, after moving from `ng-model` to `date` the angular `$validators` do not work anymore? If that is so I would revert that change.

> Now I see that you update the maxDate on on-change event... By using this approach I would have to modify a lot of code, but maybe it's a solution.

What happened is that I actually watch over all the `options` object now and if you update it I update the parameters of the datetimepicker library. That was the fastest way I could think of to allow linking datetimepickers in "from - to" pairs. 
So far I had no trouble with it in my project, but hey, I did not oversee everything :)

For the time being you can try using version `0.2.x`, the old one uses ng-model but does not allow to change `options` on the fly.

**Comment by rodrigosaling** [comment]
@atais try to access this link: http://plnkr.co/edit/JLRHoNxLBWuD7mm3IEpZ?p=preview to see my modifications.

The validation I am doing tests if the second date is before the first, and if the first date is after the second, like using maxDate and minDate, but allowing the user to select any date on both datepickers. This logic is now working, but you can try to change the year of one of the fields by typing it. The then date breaks.

Yesteryday I found another branch that also allows the use of `.input-group` https://github.com/aselby/angular-bootstrap-datetimepicker-directive. It doesn't have the `$watch` on options, but it uses the `ng-model` on the input.

**Comment by atais** [comment]
Ok I see your point now.

Please try using the new, `0.3.3` version. The directive uses ng-model again, so you should be able to put double directive around the `input-group`.

Please tell me how it worked out for you! Thanks!

**Comment by rodrigosaling** [comment]
I created a new plunker because the previous one was assigned to _Anonymous_ user instead of me. Here it goes http://plnkr.co/edit/ZxtpgNhPvm2XSDoZDysE?p=preview

I already updated library link to `0.3.3` and I am declaring the `ng-model` on the `div.input-group`. But I can't make the validators work. I think the validtor directive can't find the model to work with. And what do you mean by "put the double directive around"?

**Comment by atais** [comment]
OK. To begin with I have not used `$validators` before :-)

I investigated a little deeper, with this tutorial about $validators: http://blog.thoughtram.io/angularjs/2015/01/11/exploring-angular-1.3-validators-pipeline.html

So what I see from your plunker you would like to actually validate the date `input`, but since you attach the `datetimepicker` directive around `input-group` your input does not hold `ng-model` which you could check.

At the moment I can not think of an option you could co-op this two methods.
Even the other branch you mentioned (https://github.com/aselby/angular-bootstrap-datetimepicker-directive/commit/842f50a91c4c1d947211e66bb6468b12562c07e0) uses the `datetimepicker` directive around input so the validation would work.

However...
This is really more of a hacking - solution than making it really work, but I guess there is a chance.
You could try working with another `input` somewhere on a side, making it `display: none` and setting its `ng-model` to `vm.dateFrom`. Then putting you validator around this one and hacking the css so you mark the `input` used by directive with red color if something is wrong....

I would like to spend more time at this problem but currently I did not encounter it in my work and I am busy with something else too. But I hope we can find some solution.

**Comment by rodrigosaling** [comment]
Your MacGyver-style solution is very interesting in a case of tight deadline. I will keep it for future reference ;-)

But don't worry about time. I modified one of the aselby's commits to solve my problems, since I don't need the `$watch` on options. I really appreciate your help on this. Thanks @atais!

**Comment by atais** [comment]
@rodrigosaling can you post your modification here? So the validation works on `input-group`?
I would gladly improve this fork :-)

Thanks!

**Comment by rodrigosaling** [comment]
Hello @atais!

I created a new fork from **aselby**'s code and committed it here: https://github.com/rodrigosaling/angular-bootstrap-datetimepicker-directive/blob/master/angular-bootstrap-datetimepicker-directive.js

Sorry for late reply.

**Comment by atais** [comment]
@rodrigosaling its has been a while, but even with version `0.3.3`; if you would have attached the directive to the `input` element the validation works no problem.

Check out this plunker: http://plnkr.co/NmFt43
and also see the updated `0.3.4` version.

**Comment by rodrigosaling** [comment]
Thanks @atais for the update! But how do I make the datetimepicker open by clicking on the button instead of the input?

**Comment by atais** [comment]
That is the downside. But is it possible in **your** fork or **aselby's**?

**Comment by rodrigosaling** [comment]
I forked an old Plunker to use [my fork](https://github.com/rodrigosaling/angular-bootstrap-datetimepicker-directive/blob/master/angular-bootstrap-datetimepicker-directive.js) of the datetimepicker: http://plnkr.co/edit/S0uzzPTcUH8jwNpDGUjZ?p=preview
In this example, it uses a custom validator to check if the range of dates is correct. You can try to set the **To** date to a day before the **From** to see the validation triggering.

**Comment by atais** [comment]
Awesome! So with `0.3.4` validation is OK, but the button does not work.

To be honest I do not know why on your fork the button works, because you still use the directive on `input`... and then it is "magically" operating from `span` element as well. 

Simply said I would actually say that mine version works more like it actually should ;-)
But anyway - I am looking into this. 

Thanks for all the support!

**Comment by rodrigosaling** [comment]
I guess it's the use of `datePickerElement` with `$element`, but I am not sure either.
I really appreciate all your effort on this issue @atais. Good luck in further discoveries!

**Comment by atais** [comment]
Wow. OK it was not that hard. I did not notice that before though!

Everything seems to work. I simplified your plunker a bit and made an example here: http://plnkr.co/ZeKX7z

Looks good :-)?

Big thank you again, I hope you don't mind that I've put your name under "Special thanks" in readme.

**Comment by rodrigosaling** [comment]
Great job @atais, it's working perfectly. And thanks for the mention!
